### ISSUE TITLE
24V Noctua Mainboard Fan Replacement

### ISSUE THREAD

**Issue by DonutCatDev** [adepssimius/everything-sovol-sv08#3]
I've been able to confirm that the [24V NF-A4x10 on Amazon](https://www.amazon.com/dp/B0CN39MCPL) is a direct replacement for the stock fan, utilizing the included Molex -> JST-XH adapter cable, but it may require slightly longer M3 screws unless it's flipped. 

The sound on full power is much more tolerable but trying to software PWM the fan via default plug results in some additional cycle noise. The included "low-noise" adapter can also be used to further reduce noise at the cost of airflow.

It's also possible to print a spacer such as [this one](https://www.printables.com/model/685606-4010-fan-spacer) to reduce noise even more, but you must scale Z-height to at max ≤6mm, and ≤4mm is easier to fit.

I've used the `printer.cfg` entry below so the fan is only on when host temperature is high. 

```
[temperature_fan MCU_fan]
pin: PA1
max_power: 1.0
shutdown_speed: 1.0
kick_start_time: 0.5
off_below: 0.05
sensor_type: temperature_host
control: watermark
target_temp: 45
min_temp: 15
max_temp: 80
max_speed: 1.0
min_speed: 0.0
```

![PXL_20240512_193610717](https://github.com/adepssimius/everything-sovol-sv08/assets/19825893/bba1e376-36bb-4762-a093-cec8a4fe56ea)

**Comment by adepssimius** [comment]
Thanks for your contribution. I've added it [here](https://github.com/adepssimius/everything-sovol-sv08/commit/68f7fa5a931b014a7f6048025a9bd51b9ef328a1)
