### ISSUE TITLE
May I link to this from my repo

### ISSUE THREAD

**Issue by mon5termatt** [adepssimius/everything-sovol-sv08#5]
https://github.com/mon5termatt/SV08-Community

I'm trying to compile mods for this printer. Would it be ok to link to these files on my repo.

**Comment by adepssimius** [comment]
Definitely. These are just mods that I have found and compiled here. I have not been able to mod my printer yet since the printer that was delivered to me was DoA, so I have been less active here than I would have liked.

**Comment by mon5termatt** [comment]
Will work on linking more of it later but for now im just adding a "additional info"  section into the main page.
